name: Ruby

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu
          - macos
        ruby:
          - 2.4
          - 2.5
          - 2.6
          - 2.7
          - '3.0'
          - 3.1
          - 3.2
          # TODO: jruby, rbx

    runs-on: ${{ matrix.os }}-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: 2.3.26

    - name: Build and test with Rake
      run: |
        bundle install
        bundle exec rake
